### PR TITLE
Badge for dependencies

### PR DESCRIPTION
**Pull request by kevgo**
This PR adds a badge to track that dependencies are up-to-date. They were pretty out of date, so I upgraded them as well. The tests are still passing.

### CODE REVIEW

**Comment by igl** [comment]
Maybe without the upgrades in `package.json` it could go in.

**Comment by kevgo** [comment]
I'm happy to not update dependencies in this PR if you are fine with seeing a yellow badge on your homepage. Just let me know.

**Comment by vendethiel** [comment]
@gkz's call on this one

**Comment by gkz** [comment]
couldn't auto merge so just manually updated deps

**Pull request closed without merging**
