### PR TITLE
fix loop guards + let + destructuring issues

### LINKED ISSUE #992: When using for+let, the loop variable isn't available in the when clause
exemple:

```livescript
for let k in v when k
  ...
```

result:

```js
var i$, ref$, len$;
for (i$ = 0, len$ = (ref$ = v).length; i$ < len$; ++i$) {
  if (k) {
    (fn$.call(this, ref$[i$]));
  }
}
function fn$(k){
  throw Error('unimplemented');
}
```

expected:

```js
var i$, ref$, len$;
for (i$ = 0, len$ = (ref$ = v).length; i$ < len$; ++i$) {
  var k = ref$[i$];
  if (k) {
    (fn$.call(this, k));
  }
}
function fn$(k){
  throw Error('unimplemented');
}
```

### PR DESCRIPTION
**Pull request by rhendric**
Alternative to #994, closes #992.

### CODE REVIEW

**Comment by rhendric** [comment]
@vendethiel, review?

**Comment by vendethiel** [comment]
Seems to work in the cases I tested. I still would like if you added tests like:

nested (`for let [{a}] in b`)
with an alias (`for let {k: {v: a}} in b`)

**Comment by rhendric** [comment]
Is this better? Any more cases you think are relevant?

**Comment by vendethiel** [comment]
LGTM.

**Pull request merged**
