### PR TITLE
Betterify editor documentation

### PR DESCRIPTION
**Pull request by impinball**
"Text editor support" can imply native support within text editors themselves, as in like Atom's support for JavaScript and CoffeeScript and Eclipse's support for Java. I thought this would better convey the meaning.

### CODE REVIEW

**Comment by gabeio** [comment]
Why not Text Editor Plugins...?

**Comment by impinball** [comment]
What about this?

**Comment by gabeio** [comment]
That works :smile:

**Comment by impinball** [comment]
ping @gkz @vendethiel

**Comment by vendethiel** [comment]
@gkz is the one to ping for the website :)

**Comment by impinball** [comment]
Ok. Sorry. ;)

**Pull request merged**
