### PR TITLE
Add programmatic API documentation & some syntax highlighting

### PR DESCRIPTION
**Pull request by impinball**
Added documentation to the best of my ability of the LiveScript programmatic API. I wouldn't be surprised if I missed a few things.

Brief description of other changes:

1. My editor automatically removes trailing whitespace. That accounts for the majority of changed (not added/removed) lines.
2. I corrected a few of the categories under "Usage" for clarity.
3. I added syntax highlighting to a single `<pre>` containing HTML, starting at line 259.

### CODE REVIEW

**Comment by impinball** [comment]
If you want a different format for the type annotations/API documentation, I can change it easily enough. Also, please tell me if I made any mistakes/omissions in the API.

This is the first in a planned series of PRs I want to contribute addressing various things in the website.

@gkz, could you take a look at this?

**Comment by quarterto** [comment]
You can [add `?w=1`](https://github.com/gkz/LiveScript/pull/645/files) to the URL to ignore whitespace-only changes.

**Comment by impinball** [comment]
@quarterto Thanks for the tip ;)

**Comment by vendethiel** [comment]
Looks pretty nice! Seems to me the "nullable" question mark should be on the type side (`ex :: String?`).
I do however think we've reached the limits of a "single page doc"...

**Comment by gkz** [comment]
Thanks!

**Pull request merged**
