### PR TITLE
Add Gitter chat badge to README

### PR DESCRIPTION
**Pull request by anko**
The [LiveScript Gitter chat](https://gitter.im/gkz/LiveScript) is mainly inactive, but I think it could be great if we started using it. Since it allows github login, it would make it much easier to find other LiveScripters, and could reduce the multitude of [gh issues](https://github.com/gkz/LiveScript/issues) that are about really small problems.

I'm aware of [/r/livescript](http://www.reddit.com/r/livescript/) and [the Google Group](https://groups.google.com/forum/#!forum/livescript), but they're better oriented for large topics, don't work with a github account, and aren't "officially" endorsed either as far as I can tell.

What do you think?

### CODE REVIEW

**Comment by vendethiel** [comment]
I don't know. I prefer IRC by far. @gkz ?

**Comment by quarterto** [comment]
There is a [Gitter-to-IRC bridge](https://irc.gitter.im/).

**Comment by anko** [comment]
I forgot we had an IRC! How active is it?

Either way we decide, I think we need to reduce the friction for getting to another human. Maybe mention the subreddit, IRC and Google Group straight in the readme, or next to the other social badges on livescript.net.

At the moment it's just Twitter and Github:

shot

**Comment by anko** [comment]
@raine Great!

I see no need to duplicate the functionality that IRC clearly already provides. Closing.

**Comment by gabeio** [comment]
why not at least add irc to the readme...

**Pull request closed without merging**
