### PR TITLE
Fix tests on Node.js 7

### PR DESCRIPTION
**Pull request by rhendric**
This deck of commits fixes the two tests that were failing on Node.js 7, one of which was called out in #946, and the other of which was a REPL tab-completion bug. (While I was poking around the REPL, I also fixed a few other issues.)

### CODE REVIEW

**Comment by dk00** [comment]
Should we also add `7` to travis config (like this:)?
```
language: node_js
node_js:
  - 4
  - 6
  - 7
```

**Comment by rhendric** [comment]
Per [the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Available-Versions), I don't think Travis supports 7 yet.

**Comment by dk00** [comment]
The docs are out-of-date, see this [node 7.4 build log](https://travis-ci.org/reactjs/redux/jobs/194702715)
 Travis uses [nvm](https://github.com/creationix/nvm) to install node, we can specify any node versions supported by it.

**Comment by rhendric** [comment]
Oh, awesome! Thanks for the tip; I added 7 now.

**Comment by rhendric** [comment]
Hmm. I'll fix this; don't merge yet.

**Comment by auvipy** [comment]
@gkz

**Comment by rhendric** [comment]
@gkz, any issues with this one?

**Comment by gkz** [comment]
thanks

**Pull request merged**
