### PR TITLE
CLI: When on Windows, print Windows path separator `\` instead

### PR DESCRIPTION
**Pull request by summivox**
reason: consistency; passing test

### CODE REVIEW

**Comment by vendethiel** [comment]
Breaks the build

**Comment by summivox** [comment]
Ah damn. It seems that I have used APIs available only in the newer Node versions, namely `path.posix.join`.

Question: Would you fix the test to include windows separator `\`, or make CLI output `/` ?

**Comment by summivox** [comment]
@vendethiel : phew, now it passes even on node `v0.10.x`. Shouldn't have taken new Node APIs for granted ;)

**Comment by vendethiel** [comment]
Thanks!

**Pull request merged**
