### PR TITLE
ES7 `async`/`await` implementation with concise syntax

### PR DESCRIPTION
**Pull request by summivox**
[ES7 async/await](http://wiki.ecmascript.org/doku.php?id=strawman:async_functions) is a syntax sugar for promise+generator async control pattern. Although this feature is still a draft in even ES7, it has gained considerable traction, and is completely usable right now through [a babel plugin](http://masnun.com/2015/11/11/using-es7-asyncawait-today-with-babel.html).

This patch provides a concrete example on which we can discuss syntax extensions to LiveScript that compiles to ES7 async/await.
# `async function`
1. Append an additional `>` to all arrows: `->>`, `~>>`, `-->>`, `~~>>`
   Rationale for the syntax: terseness
2. ~~Prepend keyword `async` to arglist of arrow functions: `async (arglist) -> body`
   Rationale for the syntax: agrees with [strawman](http://wiki.ecmascript.org/doku.php?id=strawman:async_functions) proposal on async "ES6 rocket" functions~~ (redundant)
3. Prepend keyword `async` to named function definitions: `async function name(arglist)`
   Rationale for the syntax: obvious
# `await` expression
1. `await` compiles to `await` (in the same way as how `yield` is compiled now)
2. ~~`await all` compiles to `await*` (in the same way as how `yield from` is compiled now)
   Rationale:  `await*` is proposed to have the same semantics as `Promise.all` (see [strawman](http://wiki.ecmascript.org/doku.php?id=strawman:async_functions))~~ (no longer in standard)
# Example

``` livescript
af1 = (x) ->> await x
af2 = async (a, b, c) ~> await @x
async function af3(x)
  a = await af1 x
```

compiles to

``` javascript
var af1, af2, this$ = this;
af1 = async function(x){
  return (await x);
};
af2 = async function(a, b, c){
  return (await this$.x);
};
async function af3(x){
  var a;
  return a = (await af1(x));
}
```
# References
- [Official Strawman Proposal](http://wiki.ecmascript.org/doku.php?id=strawman:async_functions)
- [Example of async/await usage](http://code.tutsplus.com/tutorials/a-primer-on-es7-async-functions--cms-22367)
- [Babel plugins for transpiling ES7 async/await to ES5](http://masnun.com/2015/11/11/using-es7-asyncawait-today-with-babel.html)
- #752 #754 : prior art
- #811 : LiveScript "2.0" checklist

### CODE REVIEW

**Comment by isiahmeadows** [comment]
How would that work with libraries using that identifier? I'm working on one that could implement this general functionality at the library level, possibly more optimally than engines could. (I'm using Bluebird-style shortcuts to do it, including keeping the stack minimized.)

**Comment by summivox** [comment]
`['ID', 'async']` is left alone unless it is followed by a `PARAM(` or `FUNCTION`

**Comment by summivox** [comment]
@vendethiel decided in #752 that lsc should not transpile

**Comment by darky** [comment]
async/await almost in v8 as stable feature. Any activity here?

**Comment by isiahmeadows** [comment]
@gkz? IIRC this barely missed the V8 train for Node 7, and it's been shipping in Edge for a while.

**Comment by summivox** [comment]
My opinion:

- I don't think the syntax and semantics of async/await *in ES7* would change in any major way, now that it is being rolled out experimentally.
- The proposed syntax for LSC does not conflict with existing code, and is intended for early adopters specifically targeting ES7 (and quite possibly including further transpiling toolchain)

Therefore I believe it is safe for this to land in LSC.

**Comment by isiahmeadows** [comment]
WRT the PR itself, I feel having both `(arg) ->>` (and friends) and `async (arg) ->` is rather redundant.

**Comment by isiahmeadows** [comment]
@summivox You mean ES 8?

**Comment by summivox** [comment]
@isiahmeadows It seems that people have stopped caring about the "version number" and started to rely on shipping schedule instead. I'm fine with this ;)

Regarding syntax: Historically coffee-ish languages have this dilemma of symbols vs English words. `&&` vs `and` in LSC is a prime example --- different operator precedence (with `and` being more sane therefore the default). I don't see why both versions of arrows cannot co-exist. However, if only one is to stay, I would suggest  `->>` which stays in line with the "symbolic" feel of the arrows while retaining orthogonality, and `async function` for the "English" side.

**Comment by isiahmeadows** [comment]
There is a push to get rid of many of the duplicate operators like `&&` vs
`and` in one of the issues here. I can't remember the number right off,
though.

On Tue, Oct 25, 2016, 17:00 Yin Zhong <notifications@github.com> wrote:

@isiahmeadows <https://github.com/isiahmeadows> It seems that people have
stopped caring about the "version number" and started to rely on shipping
schedule instead. I'm fine with this ;)

Regarding syntax: Historically coffee-ish languages have this dilemma of
symbols vs English words. && vs and in LSC is a prime example --- different
operator precedence (with and being more sane therefore the default). I
don't see why both versions of arrows cannot co-exist. However, if only one
is to stay, I would suggest ->> which stays in line with the "symbolic"
feel of the arrows while retaining orthogonality, and async function for
the "English" side.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/gkz/LiveScript/pull/836#issuecomment-256174348>, or mute
the thread

**Comment by summivox** [comment]
I just tested this with node v7.3.0 . **It feels awesome.**

@isiahmeadows : I agree with you on removing `async (args) -> body` now. For anonymous functions, LSC allows only arrows while ES6 allows both `function()` and arrow. There is no good reason to keep an alternative syntax for async.

**Comment by dk00** [comment]
`await*` have been [removed](//stackoverflow.com/a/35168428/4578017) from [the proposal](/tc39/ecmascript-asyncawait), should we remove it as well, or simply compile it to `await promise.all ...` ?

**Comment by gkovacs** [comment]
Thank you for this excellent patch. I have noticed a bug when using it against the master branch ( https://github.com/gkz/LiveScript/commit/47ad4eba3a23003b4d571ac6d7e9b0c603c8950e )

```
getdict = (name) ->>
  data = await getCollection(name)
  return {[key, val] for {key, val} in data}
```

somehow gets compiled to (notice the superfluous yield*)

```
// Generated by LiveScript 1.5.0
(function(){
  var getdict, out$ = typeof exports != 'undefined' && exports || this;
  out$.getdict = getdict = async function(name){
    var data, key, val;
    data = (await getCollection(name));
    return (yield* (function*(){
      var i$, ref$, len$, ref1$, resultObj$ = {};
      for (i$ = 0, len$ = (ref$ = data).length; i$ < len$; ++i$) {
        ref1$ = ref$[i$], key = ref1$.key, val = ref1$.val;
        resultObj$[key] = val;
      }
      return resultObj$;
    }()));
  };
}).call(this);

```

**Comment by summivox** [comment]
@gkovacs : this is a separate issue: #764 #938

**Comment by gkovacs** [comment]
Thank you for the fast response! Also here's another issue. The following code compiles:

```
foo = -> ''

a = foo(async ->
  ''
)
```

And so does this:

```
foo = -> ''

a = foo ->>
  ''
```

But the following does not:

```
foo = -> ''

a = foo async ->
  ''
```

So in the example above, `->>` and `async ->` aren't quite identical.

**Comment by isiahmeadows** [comment]
Here's my proposed resolution: remove `async ->` altogether. It doesn't fit with every other anonymous function syntax.

I'm kind of 1% tied to this project now, since the parser bugs have pretty much killed this project for me, and no stable release yet has provided ES6 support.

**Comment by summivox** [comment]
I want to remove `async ->` syntax so this is a wontfix.
I just haven't been actively working on this project for a long time.

**Comment by summivox** [comment]
Hmm done.

**Comment by gkovacs** [comment]
I fixed the issue of yield* statements being generated inside async functions due to bug https://github.com/gkz/LiveScript/issues/764 in https://github.com/gkovacs/livescript-async/commit/97b86df09d66ea4c7e2f44d2b77ba6b6d4a3b130 (also removed `await all` as `await*` is no longer part of ES2017)

**Comment by yizhong-ms** [comment]
@gkovacs could you please make a PR to my branch; thanks

**Comment by gkovacs** [comment]
@yizhong-ms @summivox created a PR to your branch at https://github.com/summivox/LiveScript/pull/2/files

**Comment by determin1st** [comment]
can you post some examples of this functionality?

**Comment by determin1st** [comment]
does this update work? tried to run examples on livescript.net with no luck.

**Comment by isiahmeadows** [comment]
@determin1st This PR hasn't been merged, and livescript.net isn't updated until the next release IIRC.

**Comment by determin1st** [comment]
oh, i see. experimented with promises a little, found it useful but they are not "real" part of the language. it's like helpers. probably wont use this functionality.

**Comment by gkovacs** [comment]
@rhendric Given that the ES2017 standard (with async functions) has now been released and nodejs and all major browsers support the syntax by default, is there any chance you could review and merge this pull request? Thank you!

**Comment by rhendric** [comment]
I would be very happy to look it over! @summivox, can you confirm that this is in a state that you endorse for merging, or if there are any outstanding issues or design questions, summarize what they are?

**Comment by summivox** [comment]
@rhendric Let me quickly build and verify. I think tests need to be added.

**Comment by rhendric** [comment]
Yes please to tests. No rush from me (I'm actually running out the door right now and probably won't have free time for a few days anyway); just drop me a mention when you're ready for a review and I'll follow up when I'm able. Thanks!

**Comment by willin** [comment]
mark, pls add in asap

**Comment by willin** [comment]
can it use now?

**Comment by gkovacs** [comment]
@willin If you're impatient and want to use it now do `npm install -g livescript-async` ( https://www.npmjs.com/package/livescript-async - it is just standard livescript plus this patch, uploaded by me to NPM as I grew impatient for this to be released). But no it is not yet released in the official livescript.

**Comment by willin** [comment]
it will be great helpful if you add a documentation for this package.

**Comment by ozra** [comment]
@gkovacs - thanks for the npm! Trying it out right now.

**Comment by gkovacs** [comment]
I've added tests in a new branch https://github.com/gkz/LiveScript/pull/978 - as summivox asked this to be taken over in https://github.com/gkz/LiveScript/issues/977 I will be taking over the efforts for getting this merged

**Comment by rhendric** [comment]
#978 has landed, so I'm closing this.

**Pull request closed without merging**
