### PR TITLE
test

### PR DESCRIPTION
**Pull request by determin1st**
probably faster :/

### CODE REVIEW

**Comment by vendethiel** [comment]
Probably?

**Comment by rhendric** [comment]
> probably faster :/

I don't see why it would be, unless you have data to show that it is.

**Comment by determin1st** [comment]
well, i've tested it: https://jsperf.com/object-spread-vs-polyfill/3

oookay, at least, it's not slower... 8) 
theoretically it should be faster as it doesnt create additional variable..

**Comment by vendethiel** [comment]
I think your code gets optimized away.

**Comment by rhendric** [comment]
This is way too speculative an optimization to be worth thinking about. I'm all for contributions that make LiveScript faster, but not PRs that could maybe theoretically make it faster but that in practice have no measurable effect.

**Pull request closed without merging**
