### PR TITLE
bodyless let

### PR DESCRIPTION
**Pull request by rhendric**
This commit adds two language features involving the `let` keyword. The first is bodyless let, which permits a `let` line without an indented body to be interpreted as implicitly containing the remainder of the current block as its body, much like backcall syntax. The second is `let const` and `let var`, which are shorthands for including const or var declarations as the first line in the body of a let expression, whether that body is indented or implicit.

Resolve gkz/LiveScript#962.

---

This is a new feature which would represent some support burden going forward (it touches the lexer, although in a straightforward way), and thus deserves some attention. I'll hold this open for at least **two weeks**, merging on **May 29** if met with only apathy (there has been a relatively spirited conversation in #962 already).

### CODE REVIEW

**Comment by rhendric** [comment]
For anyone watching, I'm leaning towards not merging this. Per discussion in #962, I suspect using a scope-introducing `let` without the block demarcating the scope introduces more gotchas than it's worth.

**Comment by vendethiel** [comment]
`let const` might be a good idea however.

**Comment by rhendric** [comment]
So the question is, should `let const a = b, b = a` have the sequential assignment semantics of `const a = b, b = a`, or the swappy function argument semantics of `let a = b, b = a`?

If the former, then
```ls
let const foo = stuff
  more-stuff
```
is just shorthand for
```ls
let
  const foo = stuff
  more-stuff
```
and I don't think saving that line is especially worth it if not in service of the use case of #962. (This is what the PR implements.)

If the latter, then I think we should also be talking about consts in function parameters, like `(a, const b) -> ...`. I think this would be very interesting to pursue (if the parser ends up easily permitting it) but is nothing like what I wrote in this PR.

**Comment by vendethiel** [comment]
That's a good question, But I'm not sure `const` should be the keyword to swap between sequential  and parallel assignment. Lisps usually use `let` and `let*` (which might not be clear either, but at least not as confusing as `const`).

**Comment by rhendric** [comment]
Yeah, I take your point, although I wouldn't think of `const` as the thing that switches between assignment semantics. I was more thinking, do you interpret `let const a = b, b = a` as a `const a = b, b = a` inside a `let`? Or do you interpret it as sugar for the currently impossible `((const a, const b) -> ...) b, a`?

**Comment by vendethiel** [comment]
The latter, like `let` behaves normally.

**Comment by rhendric** [comment]
I think so too, but then I think it also behooves me to investigate allowing that syntax in functions.

**Pull request closed without merging**
