### PR TITLE
Start work on the babel pipeline

### PR DESCRIPTION
**Pull request by AriaMinaei**
As discussed in #821, these are the minimal changes required to start working on the babel pipeline.

To test it out:

``` livescript
LiveScript = require \livescript

code = """
function suma a, b
  a + c
"""

console.log LiveScript.babelPipeline.compile code
```

For now, it can only compile this code:

``` livescript
function add a, b
  a + c
```

Here is how the pipeline will probably work:
1. [`simplifyLsNode`](https://github.com/AriaMinaei/LiveScript/blob/ebd838c74ce131186614034bf577b480a2dd059a/src/babel-pipeline.ls#L13) makes LS AST easier to read with `console.log()`. This doesn't affect the rest of the pipeline, and only makes debugging easier.
2. The simplified AST is fed to [`lsASTToBabelAST`](https://github.com/AriaMinaei/LiveScript/blob/ebd838c74ce131186614034bf577b480a2dd059a/src/babel-pipeline.ls#L39). This will turn a simplified LS AST to a babel-compatible AST, similar to what `babylon.parse` returns.
3. At this point, we do have an AST that we can generate JS code from, but LiveScript's semantics, such as last-expression-gets-returned, aren't preserved. We'll need to write a bunch of babel transforms to preserve those semantics.
4. Once we have a valid babel-compatible AST with LiveScript's semantics, we can either generate JS code, like [this](https://github.com/AriaMinaei/LiveScript/blob/ebd838c74ce131186614034bf577b480a2dd059a/src/babel-pipeline.ls#L109), or feed the babel-compatible AST to babel-eslint, by changing [this line](https://github.com/babel/babel-eslint/blob/master/index.js#L6) from `var parse = require("babylon").parse` to `var parse = require('livescript').babelPipeline.parse`.

### CODE REVIEW

**Comment by auvipy** [comment]
cool

**Comment by morningrat** [comment]
No

**Comment by darrrk** [comment]
I think need to create drop-in replacement of ls-ast in favor to babylon-ast.
That is:

    ls-tokens -> babylon-ast

instead

    ls-tokens -> ls-ast -> babylon-ast

Must be more faster, flexible and robust.

**Comment by vendethiel** [comment]
no, that'd leave the burden of transformating Ls constructs to the lexer/grammar, which is a bad idea. It's probably better to have a "toBabelNode" or something on the AST directly (exactly in the same way we recursively compile nodes to js fragments)

**Comment by JoyKrishnaMondal** [comment]
babel sucks - enuf said.

**Comment by vendethiel** [comment]
@JoyKrishnaMondal That's both inconstructive and uninteresting. Let's avoid this kind of comments.

**Comment by JoyKrishnaMondal** [comment]
Fine, 

Babel 6 requires a .babelrc file ( dafaq ? you guys are just a compiler - stop trying to make a platform happen - its not going to happen ) 

Babel documentation is a lot less helpful then the community is ready to admit - half the stuff is not updated to reflect recent changes. 

ES6 exists on a much lower level in terms of programming language compared to livescript - why it gets more attention is beyond my comprehension. 

Babel is more concerned about marketing then improving docs or the code itself. 

The babel community is much more dismissive then any other OSS community I have seen out there - I personally just follow their issues rather than use babel myself.

these are just some of the problems I have with babel. I just do not want babel to dominate and replace typescript,live-script,coffeescript . . .  just because they have a better marketing team.

**Comment by AriaMinaei** [comment]
@JoyKrishnaMondal This better be discussed in #821. Please read my first post where I explain why I think we should this.

**Comment by AriaMinaei** [comment]
I like @vendethiel's idea that we just add a `::toBabelNode()` method to each `Node` class. But I don't know if it'll be cleaner and more maintainable than `lsASTToBabelAST`. Let me do a little experiment and let you know how it goes.

**Comment by vendethiel** [comment]
`lsASTToBabelAST` is basically a huge switch/case, whereas our current approach in the codebase is to use OO.

**Comment by tomByrer** [comment]
Any progress?

**Comment by auvipy** [comment]
really looking forward to see this moving ahead

**Comment by determin1st** [comment]
@AriaMinaei 

it's a lot of work to sync those, but benefits are not clear. intellisense?

**Comment by AriaMinaei** [comment]
Closing in favor of [livescript-next](https://github.com/dk00/livescript-next)

**Pull request closed without merging**
